### ISSUE TITLE
Feature request: setting translation format

### ISSUE THREAD

**Issue by gnagno** [svenfuchs/i18n#103]
Hello,

right now when if I have in my app some code like
```    
<%= t :test %>

``````
and there is no translation available for :test I get something like this in my html:
```    
<span class="translation_missing" title="translation missing: en.test">Test</span>
``````

would it be possible to add a configuration parameter so that I can make something like 
```   
 <%= t :test, :format => 'html' %>

``````
and even if the translation is present I would get in my html something like this:
```    
<span class="translation_present" title="translation present: en.test">Test</span>
``````

This would be very useful for a plugin I am developing ( https://github.com/gnagno/lost_i18n_translation ) that will allow to have on the view a link to allow developers to add translations directly from the web interface. This way every string will be in his context and the work of translators would be easier.

My idea is to use jquery to activate a popup or a baloon tip on each translated or not translated string in the application ( this is why I am requesting to add this modification) where translators can add the text for the current locale.

thank you in advance 
Ignazio

**Comment by radar** [comment]
Closing as this is an old feature request and it does not have an associated PR.
