### ISSUE TITLE
I18n.backend.translate error when default is empty

### ISSUE THREAD

**Issue by vraravam** [svenfuchs/i18n#120]
Rails' ActionView::Helpers::NumberHelper methods (number_to_currency, number_to_percentage) call to its own number_with_precision - which in turn call i18n's I18n::Backend::Base.translate.
The calling example is: 

``` ruby
    I18n.translate(:'number.format', :locale => options[:locale], :default => {})
```

As you can see, the last parameter is an empty hash. Tracing this into the I18n::Backend::Base.translate will result in:

``` ruby
        if options.empty?
          entry = resolve(locale, key, entry, options)
        else
          count, default = options.values_at(:count, :default)
          values = options.except(*RESERVED_KEYS)
          # ************ START BUG FIX ************
          entry = entry.nil? && default.present? && !default.empty? ?
          # ************ END BUG FIX ************
          # ************ START ORIGINAL CODE ************
          # entry = entry.nil? && default ?
          # ************ END ORIGINAL CODE ************
            default(locale, key, default, options) : resolve(locale, key, entry, options)
        end
```

The fix is in the above lines of code. Could you please include it in the next version?

**Comment by radar** [comment]
With a `config/locales/pl.yml` file in my Rails app, calling `I18n.translate(:'number.format', :locale => :pl, :default => {})` returns `{}` on i18n 0.7.0.

If there's still a bug here, please let me know how I can reproduce it.
