### ISSUE TITLE
localize numbers

### ISSUE THREAD

**Issue by eloyesp** [svenfuchs/i18n#135]
I18n#localize work for dates and times, but not for numbers and it could be helpfull.

Rails stores a lot of information for localize numbers, to use "," instead of ".", to append currency symbol, etc. I think localize should implement some of this features and rails should call them instead (like it do with localize).

I want to implement this, but I want to know if it could be accepted before I start coding.

**Comment by radar** [comment]
I believe what you're after is like https://metacpan.org/pod/CLDR::Number, but for I18n. 

I'd be interested in reviewing a pull request which adds support for this. I think it should be a separate method, such as `localize_number`.

**Comment by radar** [comment]
There's a more extensive discussion over on #278.
