### ISSUE TITLE
no language fallback if :default is a hash

### ISSUE THREAD

**Issue by bughit** [svenfuchs/i18n#137]
``` ruby
require "i18n"
require "i18n/backend/fallbacks"
I18n::Backend::Simple.send(:include, I18n::Backend::Fallbacks)
I18n.default_locale = "en-au"
I18n.backend.store_translations :en, foo: {a: "a"}
p I18n.t("foo", default: {})
```

Since translate can retrieve whole sub-trees not just strings, would it not make sense for fallback to work as with strings?
The code comments says that only symbol defaults take precedence over fallback locales

**Comment by radar** [comment]
I am unable to reproduce this issue on i18n 0.7.0. Thanks for the reproduction steps!
