### ISSUE TITLE
.hash is not consistent for Strings in 1.8

### ISSUE THREAD

**Issue by the8472** [svenfuchs/i18n#146]
I'm using REE 1.8 + Passenger which forks multiple processes and a memcache as i18n cache. The cache backend uses the following line to generate the cache keys: 

``` ruby
        "i18n/#{I18n.cache_namespace}/#{locale}/#{key.hash}/#{USE_INSPECT_HASH ? options.inspect.hash : options.hash}"
```

Since passenger runs forks multiple processes and both the key and the options.inspect can be/are strings each process might generate a different hash for the same lookup. I.e. the cache has to store values separately across processes.

converting the key and inspect output to a symbol first would result in consistent hashes and thus improve cache hits on 1.8

From the console:

```
1.8.7 :001 > "foobar".hash
 => -430229383 
1.8.7 :002 > exit

...

1.8.7 :001 > "foobar".hash
 => 95537936 
```

**Comment by radar** [comment]
Thanks everyone. I'm going to wait for #285 to be completed, and then we'll have a fix for these issues.
