### ISSUE TITLE
Passing a hash with string keys for interpolation

### ISSUE THREAD

**Issue by robotmay** [svenfuchs/i18n#149]
It would appear that you can't pass a hash with string keys for interpolation, e.g.

``` yaml
en:
  example: "Oh, hello %{name}"
```

``` ruby
I18n.t("example", { 'name' => 'Jim' })
```

This will raise a MissingInterpolationArgument exception. This looks like an easy fix if the following methods are used universally, but it otherwise might be a missing/unsupported feature of Ruby interpolation in general: https://github.com/svenfuchs/i18n/blob/master/lib/i18n/interpolate/ruby.rb

**Comment by radar** [comment]
Use symbols instead. It's easier for us to support symbols only than both strings and symbols.
