### ISSUE TITLE
Exception message encoding is ASCII-8BIT, not UTF-8

### ISSUE THREAD

**Issue by jpgeek** [svenfuchs/i18n#162]
When calling
I18n.t( 'nonexistent_key' , :locale=> :en)
It returns a string: 
"translation missing: en.nonexistent_key"
This is all well and good, but the encoding of the key is ASCII-8BIT, not UTF-8.

Adding a UTF-8 encoding magic comment to:

lib/i18n/exceptions.rb
fixes the problem.

**Comment by radar** [comment]
I cannot reproduce this issue. The string that I get back is a UTF-8. If you're still able to reproduce this issue, please provide steps to do so.
