### ISSUE TITLE
Invalid fallback when trailing separator exists in a key

### ISSUE THREAD

**Issue by killthekitten** [svenfuchs/i18n#197]
To explain a problem, I wrote a simple helper, that displays translation for an object field `kind`:

```
# config/locales/ru.yml

ru:
  node:
    kinds:
      first: "Первый"
      second: "Второй"
```

```
# app/helpers/nodes_helper.rb

module NodesHelper
  def node_kind(value)
    t("node.kinds.#{value}", default: 'blank')
  end
end
```

Here is what I expected:

```
node_kind('first') # => "Первый"
node_kind(nil)     # => "blank"
```

And here is the real behavior:

```
node_kind('first') # => "Первый"
node_kind(nil)     # => {:first=>"Первый", :second=>"Второй"}
```

Let's see, what happens behind the scenes. I18n has a `normalize_key` method:

```
# gem/lib/i18n.rb

def normalize_key(key, separator)
  normalized_key_cache[separator][key] ||=
    case key
    when Array
      key.map { |k| normalize_key(k, separator) }.flatten
    else
      keys = key.to_s.split(separator)
      keys.delete('')
      keys.map! { |k| k.to_sym }
      keys
    end
end
```

When we pass `nil` as an argument to `node_kind`, here is what happens: 
1. It calls `t("node.kinds.#{nil}")` (notice that key has trailing separator `"node.kinds."` in this case).
2. `normalize_key` splits `key.to_s` and throws out last element (a blank value, caused by trailing separator).
3. It recognizes `node.kinds` locale entry and returns a hash.

Is it the way the `normalize_key` method should behave? Or is it a bug?

**Comment by radar** [comment]
I agree with @tigrish's assessment of this issue.
