### ISSUE TITLE
Uppercased modifiers ignored by locale?

### ISSUE THREAD

**Issue by ggarnier** [svenfuchs/i18n#210]
I'm using some date/time modifiers with Date#strftime, but it seems locale doesn't work for uppercased modifiers.

Example:

``` ruby
I18n.l(Date.new(2013, 07, 01), format: "%B", locale: :es)
=> "julio"
```

``` ruby
I18n.l(Date.new(2013, 07, 01), format: "%^B", locale: :es)
=> "JULY"
```

**Comment by radar** [comment]
I think that #347 will provide a way for you to work around this problem.
