### ISSUE TITLE
method translate return array instead of string

### ISSUE THREAD

**Issue by largobox** [svenfuchs/i18n#211]
Good day. I try do following (in rails console for example) :
 I18n.t("devise.sessions.new.title")
And i get that -  ["Sign In"]

In my yml file i have that:
en:
  devise:
    sessions:
      new:
        title: "Sign In"

Before I get string (don`t array) and all will be fine, why now am i get array instead of string?

**Comment by radar** [comment]
Hey @largobox. The indentation on your `yml` wasn't preserved here, so I don't know how you were able to get an array. 

I just tried it in an app which is using 0.7.0, albeit with a properly intended yaml file:

```yaml
en:
  devise:
    sessions:
      new:
        title: "Sign In"
```

This works for me.

If you have steps to reproduce the issue, then I will re-open this issue and investigate.
