### ISSUE TITLE
CLDR v24 and pluralization

### ISSUE THREAD

**Issue by jhass** [svenfuchs/i18n#214]
The upcoming release of the CLDR, v24, will make substantial changes to the pluralization rules. See https://docs.google.com/document/d/155ZJOHtOgnm8P80TDL8QGfNZ-wNoqsRNRGHRfJB4JGs/edit?pli=1 for the draft.

I wonder if there are any plans to support these or if we should prepare to embed the computation of the new variables into the rules if we want to use that data.

**Comment by radar** [comment]
@bdurand Could you please submit a PR to fix up these breakages?

**Comment by bdurand** [comment]
It looks like the Unicode Consortium rolled back the change to Russian pluralization in [CLDR version 25](http://www.unicode.org/cldr/charts/25/supplemental/language_plural_rules.html) on March 18, 2014 to have the "few" rule again so my issue is solved.

**Comment by radar** [comment]
Great! Then I am going to go ahead and close this issue.
