### ISSUE TITLE
Lambda translations and pluralization problems

### ISSUE THREAD

**Issue by hexdigest** [svenfuchs/i18n#219]
When using pluralization and lambda translations together pluralize method returns Proc object that interpolate method leaves as it is. So finally I18n.t method returns Proc object instead of translated string.

This is how i monkey-patched this problem:

``` ruby
module I18n
  module Backend
    module Base
      include I18n::Backend::Transliterator

      def interpolate(locale, string, values = {})
        if string.is_a?(::Proc) && !values.empty?
          I18n.interpolate(string.call("", values), values)
        elsif string.is_a?(::String) && !values.empty?
          I18n.interpolate(string, values)
        else
          string
        end
      end
    end
  end
end
```

lambda translation example:

``` ruby
# encoding: utf-8
{:ru => {
  :active_admin => {
    :batch_actions => {
      :succesfully_destroyed => {
        :one => lambda {|k,o| "Успешно удалено: %{count} " + RU.count(o[:model], o[:count])},
        :few => lambda {|k,o| "Успешно удалено: %{count} " + RU.count(o[:model], o[:count])},
        :many => lambda {|k,o| "Успешно удалено: %{count} " + RU.count(o[:model], o[:count])}
      }
    }
  }
}}
```

**Comment by radar** [comment]
Could you please submit a patch to fix this issue? Thank you.

**Comment by hexdigest** [comment]
I'll do it in a week

**Comment by hexdigest** [comment]
@radar Hi, I looked at this issue again and found out that I was using lambdas as keys in the hash of pluralized values:
```ruby
key: {
  one: lambda {|key, options| ...},
  few: lambda {|key, options| ...},
}
```

According to the tests the correct way is to make lambda return a hash containing pluralized forms:
```ruby
test "pluralization: given a key resolves to a Proc that returns valid data then pluralization still works" do
  proc = lambda { |*args| { :zero => 'zero', :one => 'one', :other => 'other' } }
  assert_equal 'zero',  I18n.t(:default => proc, :count => 0)
  assert_equal 'one',   I18n.t(:default => proc, :count => 1)
  assert_equal 'other', I18n.t(:default => proc, :count => 2)
end
```

I think you can close the issue but it would be great to mention the correct way of using lambda translations with pluralization somewhere in the documentation.

Thanks.

**Comment by radar** [comment]
Thanks @hexdigest!

I am not sure where this should be mentioned in the documentation. If you can find a good place for this, then please submit a patch.
