### ISSUE TITLE
Error when using default_locale and enforce_available_locales set to true

### ISSUE THREAD

**Issue by robinboening** [svenfuchs/i18n#224]
Hi

In my `application.rb` I have defined a default_locale for i18n.

```
config.i18n.default_locale = :de
```

I do have a `config/locales/de.yml` with correct syntax.
When I now add `I18n.enforce_available_locales = true` it raises `InvalidLocale` Error on server boot.

Backtrace:

```
/Users/robin/.rvm/gems/ruby-1.9.3-p327/gems/i18n-0.6.9/lib/i18n.rb:288:in `enforce_available_locales!': :de is not a valid locale (I18n::InvalidLocale)
from /Users/robin/.rvm/gems/ruby-1.9.3-p327/gems/i18n-0.6.9/lib/i18n/config.rb:32:in `default_locale='
from /Users/robin/.rvm/gems/ruby-1.9.3-p327/gems/i18n-0.6.9/lib/i18n.rb:35:in `default_locale='
from /Users/robin/.rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.16/lib/active_support/i18n_railtie.rb:60:in `block in initialize_i18n'
from /Users/robin/.rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.16/lib/active_support/i18n_railtie.rb:53:in `each'
from /Users/robin/.rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.16/lib/active_support/i18n_railtie.rb:53:in `initialize_i18n'
```

Any ideas?

Thanks

**Comment by southfox** [comment]
Thanks to @tigrish.

I've fixed the issue with locale: "Error when using default_locale and enforce_available_locales set to true", in the log:
```
/home/vagrant/.rvm/gems/ruby-2.3.1@tamle/gems/i18n-0.7.0/lib/i18n.rb:284:in
 enforce_available_locales!': :es is not a valid locale (I18n::InvalidLocale)
```


I've fixed this using in **config/application.rb**
```
    config.i18n.enforce_available_locales = true
    config.i18n.default_locale = :es
    config.i18n.load_path += Dir[Rails.root.join('my', 'locales', '*.{rb,yml}').to_s]
```

Editing **Gemfile** and adding **gem 'rails-i18n'**

```
vim Gemfile
gem 'rails-i18n'
bundle install
```
And having the 2 files: **config/locales/es.yml** and **config/locales/en.yml**
```
es:
  Home: "Inicio"
en:
  Home: "Home"

```
And in my **app/views/layouts/_header.html.erb**
`        <li><%= link_to t("Home"),   root_url %></li>
`

Now works!

**Comment by radar** [comment]
Is anyone able to still reproduce this issue?

**Comment by sandstrom** [comment]
Since this is an old issue I'd suggest closing it. It can be reopened if someone has a reproduction or if it's still an issue.

**Comment by radar** [comment]
Agree. Willing to reopen if someone has a way to reproduce this.
