### ISSUE TITLE
0.5.2 interpolation of default option containing %

### ISSUE THREAD

**Issue by jcstringer** [svenfuchs/i18n#228]
I've run into an issue that has cropped up since bumping from 0.5.0 to 0.5.2. It has to do with the :default option passed in when that option contains a % sign. Here is an example, this issue was not happening with 0.5.0 for me. 

Without the :default, I get no errors. This app assumes the key name is the symbolized version of the string and in this simple test there is no translation for the key I'm using. 

```
1.9.3p484 :001 > string = "20% Off"
 => "20% Off"
1.9.3p484 :002 > helper.translate(string.to_sym)
[deprecated] I18n.enforce_available_locales will default to true in the future. If you really want to skip validation of your locale you can set I18n.enforce_available_locales = false to avoid this message.
 => "<span class=\"translation_missing\" title=\"translation missing: en.20% Off\">20% Off</span>"
```

When I pass in a :default option this now fails

```
1.9.3p484 :003 > helper.translate(string.to_sym, :default => string)
ArgumentError: malformed format string - %O
```

From looking at the source I think the issue tracks back to this commit
https://github.com/svenfuchs/i18n/commit/e8d5820a3b08eeca28de1a2b9c8a6ad2b9e6476c#diff-3f17a1b2013dc8b6a9e8a58094b475f8L170

From my local testing my theory is that String#% is attempting to use sprintf style formatting on value when it sees the % sign and is trying to format with %O, although I'm not sure why it omits the space between % and O. I did throw a few other tests at it and it's not specific to O, it omits the space universally.

Is this expected behavior with the way you would want the interpolation to work with the :default option or is this a valid issue? Seems like I can't be the only one who has suddenly seen issues with translated strings following this version change?

Would it make sense to rescue from an ArgumentError in this case?

**Comment by radar** [comment]
I can no longer reproduce this issue on the master branch. If you can reproduce it, let me know and I'll re-open
