### ISSUE TITLE
How should we pluralize generic "objects" count correctly

### ISSUE THREAD

**Issue by MOZGIII** [svenfuchs/i18n#239]
This problem is around for quite some time, and I've spent time time thinking on it and discussing it with people.

So, what's the problem? The problem is that we're trying to implement localization of something like generic "records" or "objects" without count, we, usuially, do it by calling something like `I18n.t(:record, count: 2)` to trigger the correct (`:other` for english) pluralized form, which works perfectly for english and _some_ other languages, but in general it doesn't.
I don't know the propper way to do it, but, eventually, if you pass `2.1` as `:count`, it works for a greater amount of languages, but not for all.
Look here for discussion: https://github.com/gregbell/active_admin/pull/2791

So, how can we manage pluralization of generic objects? I think this is a matter of fixing the API a bit, allowing something like `:count => :generic` option to be passed to `I18n.t`, which would internally fetch the propper language field for generic counts of the language. This field should be specified on a per-language basis, in the same place the pluralization rules are defined. For example, for Russian, English and French it should be `:other`, for Polish and Czech it should be `:few` (https://github.com/gregbell/active_admin/issues/1577).

What do you think?

UPD: Fixed the issue text. Now it makes sense.

**Comment by radar** [comment]
Looks like there is a work around shown in the issues above. 

If you'd like this issue fixed in i18n proper, please open a PR.
