### ISSUE TITLE
Not loading when available_locales is set

### ISSUE THREAD

**Issue by jokklan** [svenfuchs/i18n#253]
Hi

I have a rails app, and when i set the `available_locales` to ANY value, is the translation not loaded, and i get "missing translation" everywhere. However this is only in production, not in development or test.

My configuration looks like this:

``` ruby
# config/initializers/locale.rb
I18n.load_path += Dir[Rails.root.join('config', 'locales', '*.{rb,yml}')]
I18n.available_locales = [ :en, :da ] # Will not load translations, unless this line is removed.
I18n.enforce_available_locales = true
I18n.default_locale = :da
I18n.locale = :da
```

Any suggestions?

**Comment by radar** [comment]
I am unable to reproduce this issue on the latest master version of i18n.

If you're able to reproduce this issue, please let me know and I'll investigate.

Thanks!
