### ISSUE TITLE
Make `#initialized?`, `#init_translations` and `#translations` as common API for backend and change their behaviour

### ISSUE THREAD

**Issue by PikachuEXE** [svenfuchs/i18n#254]
https://github.com/fnando/i18n-js/issues/59
We need some common methods for initializing backend and getting all translations. 

==Expected Behaviour==
**`#init_translations`**
Only do expensive loading if not done already (`#initialized?`)
**`#translations`**
Calls `#init_translations`, then return all translations

==Current Behaviour==
**`#init_translations`**
Always do expensive loading if not done already (`#initialized?`)
**`#translations`**
Does not call `#init_translations`, return empty translations if not initialized
`#init_translations` only be called in `#lookup`

**Comment by radar** [comment]
Please submit a patch to fix this. Thanks.

**Comment by oniofchaos** [comment]
@PikachuEXE @radar since #353 got merged it looks like this can be closed?
