### ISSUE TITLE
Can't set locale to something other than the default

### ISSUE THREAD

**Issue by rubys** [svenfuchs/i18n#275]
[test case](http://intertwingly.net/projects/AWDwR4/locale.html) - regression introduced by https://github.com/svenfuchs/i18n/commit/b5703d7431ecfc1b99409e16c6590448570718ac

**Comment by willywg** [comment]
Try with:

```ruby
Rails.application.config.i18n.default_locale = :es
Rails.application.config.i18n.locale = :es
```

**Comment by radar** [comment]
Seems like the solution here is to set it using `Rails.application.config.i18n.default_locale`.
