### ISSUE TITLE
Site/documentation is down

### ISSUE THREAD

**Issue by leobalter** [svenfuchs/i18n#276]
http://rails-i18n.org/wiki is down for several days, not responding.

Is there any source of the documentation so I can rely on that until the site is up again?

**Comment by berlincount** [comment]
Maybe transitioning to the quite reliable github pages would make sense?

**Comment by mp-jwolkerstorfer** [comment]
If there's no move to bring back the wiki, please update the README to remove the reference to the dead page, and ideally link to the best new documentation source.

Relatedly, some of the GitHub wiki pages refer to another dead site as the source, and the new host for those source posts is http://svenfuchs.com/.

**Comment by radar** [comment]
Please refer to my comments in #323
