### ISSUE TITLE
Accept hash of string as parameter

### ISSUE THREAD

**Issue by cyrilchampier** [svenfuchs/i18n#290]
yml:

```
  model3d_errors:
    AGT_FMT: "This file is not in a valid 3d format (%{path})."
```

this works:
`I18n.translate('model3d_errors.AGT_FMT', {path: 'truc'})`
this also:
`I18n.translate('model3d_errors.AGT_FMT', { 'path'.to_sym => 'truc' })`
this not:
`I18n.translate('model3d_errors.AGT_FMT', { 'path' => 'truc' })`

Would it be possible to accept strings or syms as hash keys ?

**Comment by radar** [comment]
Use `symbolize_keys` before passing args to this method.
