### ISSUE TITLE
hash.slice will crash if keep_key is not in the original hash

### ISSUE THREAD

**Issue by brettcave** [svenfuchs/i18n#291]
lib/i18n/core_ext/hash.rb#L4 will crash if `:some_key` is in `keep_keys` but not in the hash.

A safe way to allow keep_keys to be passed to the slice function that are not in the hash is to add a if has_key?(key):

    keep_keys.each { |key| h[key] = fetch(key) if has_key?(key) }

**Comment by chrismar035** [comment]
I believe this was fixed with https://github.com/svenfuchs/i18n/pull/289 and can be closed.

**Comment by carlosantoniodasilva** [comment]
Thanks.
