### ISSUE TITLE
Allow to pass nil to localize

### ISSUE THREAD

**Issue by sobrinho** [svenfuchs/i18n#294]
Hello guys,

I would to be able to specify if I want a exception or not when passing a nil value to `I18n.localize` method.

It's a common pattern to do this on rails applications:

``` erb
<%= f.text_field :birthdate, :value => I18n.localize(person.birthdate) %>
```

And the field may or may not have the value (new records doesn't have at all). I thought in something like that:

``` erb
<%= f.text_field :birthdate, :value => I18n.localize(person.birthdate, raise: false) %>
```

It was previously requested on #154 but the idea is to allow the user to specify if the exception is important or not, defaulting to raise on nil.

Wdyt?

**Comment by lime** [comment]
In my use case, it would make sense to pass a default / fallback string to return when the value is `nil`.
```ruby
person.birthdate ? I18n.l(person.birthdate) : '-'
```
```ruby
I18n.l(person.birthdate, fallback: '-')
```
Though I'm not sure if it should only apply to `nil`, or all invalid values.

Any input from the maintainers on this, are you at all open to considering something other than always raising an error?

**Comment by sobrinho** [comment]
For a fallback you could use:

``` ruby
I18n.l(person.birthdate) || "-"
```

**Comment by lime** [comment]
> For a fallback you could use:
> ```
> I18n.l(person.birthdate) || "-"
> ```

Well, only if I myself patch `I18n.l` to let `nil` pass through, or if that change is accepted by the maintainers.

What I meant was, if the maintainers are not open to _that_ change, maybe we could be allowed to pass a `:fallback` option for the cases where we want `nil` not to raise.

**Comment by momolog** [comment]
Agreed, this is important. Either allowing `:fallback` or providing a `!`-version of the `localize` method would solve this.

**Comment by radar** [comment]
I think doing the `person.birthdate ? I18n.l(person.birthdate) : '-'` version of this code is sensible. It is only a small addition to your own codebase, and it is relatively easy to create your own `localize!` method in a helper if the behaviour is what you want.

Adding this feature to i18n is not worthwhile, I think, when the fix is so easy in your own application.

If you feel strongly against that, then please submit a PR with the `localize!` method and we can discuss use-cases there.

**Comment by ashwinvidiyala** [comment]
This discussion helped me guys. Thanks!

**Comment by cesartalves** [comment]
Hey @radar, could I open a PR for this one?  Seems like a pretty simple change and I have to deal with this in different projects from time to time.

**Comment by cesartalves** [comment]
For anybody looking, nowadays you can just do `localize(object, default: '')`
