### ISSUE TITLE
Wiki website is down as of now :(

### ISSUE THREAD

**Issue by berlincount** [svenfuchs/i18n#309]
count@orbit:~$ host ruby-i18n.org
ruby-i18n.org has address 81.169.139.174
ruby-i18n.org mail is handled by 100 mxlb.ispgateway.de.
ruby-i18n.org mail is handled by 10 ruby-i18n.org.
count@orbit:~$ ping -c 5 ruby-i18n.org
PING ruby-i18n.org (81.169.139.174) 56(84) bytes of data.

--- ruby-i18n.org ping statistics ---
5 packets transmitted, 0 received, 100% packet loss, time 4007ms

count@orbit:~$ curl --connect-timeout 10 http://ruby-i18n.org/wiki
curl: (28) connect() timed out!

**Comment by sbull** [comment]
Looks like a dup of https://github.com/svenfuchs/i18n/issues/276

**Comment by carlosantoniodasilva** [comment]
Yes, thanks.
