### ISSUE TITLE
Use `def_delegators` instead of `module_eval` for delegation code

### ISSUE THREAD

**Issue by PikachuEXE** [svenfuchs/i18n#314]
Refer to https://github.com/svenfuchs/i18n/blob/master/lib/i18n.rb#L27

**Comment by carlosantoniodasilva** [comment]
Is there any performance consideration we need to have? For example, `I18n.locale` is likely called a lot on all Rails apps, could we introduce any performance penalty by using `def_delegators`, or are we gaining anything? Thanks for the suggestion.

**Comment by PikachuEXE** [comment]
OK, I suggest this too early :P
https://gist.github.com/sstelfox/15e1b500264c75636069

**Comment by carlosantoniodasilva** [comment]
Thanks for sharing the bench :+1:

**Comment by PikachuEXE** [comment]
Maybe it's worth mentioning in code with comment? :P

**Comment by carlosantoniodasilva** [comment]
Well, maybe... however if someone accidentally removes that, at least one test would fail, perhaps that's good enough?

**Comment by PikachuEXE** [comment]
I mean the reason of using `module_eval` instead of `def_delegators`

**Comment by carlosantoniodasilva** [comment]
Ah yeah, I got confused between the two issues :smile:, sounds fine yeah.
