### ISSUE TITLE
caching available_locales breaks if the backend loads new locales

### ISSUE THREAD

**Issue by lnussbaum** [svenfuchs/i18n#315]
Hi,

This commit: https://github.com/svenfuchs/i18n/commit/a65fffd6f0472bc413ba41809dafc6292e29d2ae
breaks stringex, as shown in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=770194
and https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=765124

The broken scenario is:
- @@available_locales is not set
- the available_locales_set function gets called.
- it calls the available_locales function to get the currently available locales
- since @@available_locales is not set, it takes it value from backend.available_locales
- the Set is created

Later:
- the available locales in the backend gets modified (using store_translation, for example, like in the stringex test suite)
- but the available_locales= function never gets called
- when the available_locales_set gets called, there's no reason to refresh the cache

So, when a backend changes its status in a way that modifies what it would return from backend.available_locales, it should trigger an update of the @@available_locales_set variable.
(or the cache should just be removed, and the caching should be moved to the relevant backends)

**Comment by radar** [comment]
Hi @inussbaum, I have a fix for a similar issue in another branch (https://github.com/svenfuchs/i18n/tree/173-reset-load-path). Could you please submit a similar PR which would fix this issue?

Thanks!

**Comment by radar** [comment]
Actually, both bug reports that you've linked to say that the bug was fixed in 0.6.11. I'm therefore going to close this issue.

If you're still able to reproduce it in the latest version of i18n, let me know by providing some exact steps to reproduce it and I'll reopen this issue and investigate.

Thanks.
