### ISSUE TITLE
available_locales() includes :de when it shouldn't

### ISSUE THREAD

**Issue by KevinVerre** [svenfuchs/i18n#317]
I'm assuming that if you don't explicitly set I18n.available_locales= then I18n will automatically set it based on the translation YAML files in found the load path.

In my load path, I only had files to support locales :en and :es

But when I called I18n.available_locales it returned [:en, :es, :de] . Even thought :de was no where in the load path. I have no idea where it was getting :de from. Does anyone have a guess?

The workaround was that I explicitly set the value using this statement:
config.i18n.available_locales = [:en, :es]

This could very well be something wrong with my server. But it seems strange to me that the incorrect locales persisted.

**Comment by carlosantoniodasilva** [comment]
This extra locale might be from some gem somewhere in your application, I18n should not be adding anything to available_locales, it only loads the ones available in locale files.

Can you search for the gems in your project and trying to find which one might be the culprit? I'd bet that's the case.

Thanks.

**Comment by radar** [comment]
Agree with above. Likely comes from a gem.
