### ISSUE TITLE
http://ruby-i18n.org/wiki

### ISSUE THREAD

**Issue by mindware** [svenfuchs/i18n#323]
This site appears to be unresponsive. If there is content there, such as examples of usage, perhaps they should be moved to the github wiki?

**Comment by arthurnn** [comment]
Yes, we should move to GitHub wiki.
Anyone has access to the old content?

**Comment by mindware** [comment]
Hi @arthurnn. If no one does, as a last resourt we could probably use the Internet Archive's:
https://web.archive.org/web/20140426174216/http://ruby-i18n.org/wiki

**Comment by ptarjan** [comment]
+1

**Comment by radar** [comment]
Please refer to this project's wiki for the time being https://github.com/svenfuchs/i18n/wiki.

@svenfuchs: when you get a moment, could you please update the description of the repo to point to the wiki also?

**Comment by dmitry** [comment]
Duplicate of https://github.com/svenfuchs/i18n/issues/276

**Comment by sandstrom** [comment]
friendly ping @svenfuchs

**Comment by lulalala** [comment]
friendly ping @svenfuchs again, could you please update the description of the repo to point to the wiki?
