### ISSUE TITLE
Missing :many in Polish pluralization

### ISSUE THREAD

**Issue by ezwelty** [svenfuchs/i18n#339]
(incoming via https://github.com/Locale/localeapp/issues/189)

The CLDR plural rules (http://www.unicode.org/cldr/charts/29/supplemental/language_plural_rules.html) for Polish (pl) specifies four keys: one, few, many, and other. And rails-i18n reflects this (https://github.com/svenfuchs/rails-i18n/blob/master/spec/unit/pluralization_spec.rb#L567).

However, the i18n plural rules only define one, few, and other for Polish pluralization. Via Localeapp which uses i18n, the missing many key results in dreadful I18n::InvalidPluralizationData errors.

**Comment by radar** [comment]
Hi @ezwelty, could you please submit a PR for this?

**Comment by radar** [comment]
Fixed by #346.
