### ISSUE TITLE
Pluralization with Redis KeyValue backend does not work

### ISSUE THREAD

**Issue by ryan2johnson9** [svenfuchs/i18n#340]
Hi, 
I have 
    rails-i18n-4.0.8
    i18n-0.7.0

When I setup my backend to a redis KeyValue store, I get errors with pluralizations such as

```
id: 
  activerecord:
    models:
      user:
        other: "pengguna"
```

when I run 

`I18n.t("activerecord.models.user", count: 1)`

I get error

`I18n::InvalidPluralizationData: translation data {:other=>"pengguna"} can not be used with :count => 1`

But with backend set to standard it works.

Also notably, this is not found

```
I18n.t(:'i18n.plural.rule', :locale => 'en', :resolve => false) 
```

=> "translation missing: en.i18n.plural.rule"

but the above is found with standard backend.

My i18n.rb initializer looks like this:

  `I18n.backend= I18n::Backend::KeyValue.new(Redis.new(db: 0, password: Rails.application.secrets.redis_local_pw))`

If I change it to a chained backend then my problem is solved, e.g.

```
I18n.backend= I18n::Backend::Chain.new(
  I18n::Backend::KeyValue.new(Redis.new(db: 0, password: Rails.application.secrets.redis_local_pw)),
  I18n.backend
) #need chained backend because pluralization is not working with only KeyValue backend
```

Is this normal, or should pluralizations work with KeyValue backend only?

Also, is there a performance cost for using a chained backend for i18n?

p.s. I have a pluralization initializer that seems to have no effect whether I use it or not, it looks like this

```
require "i18n/backend/pluralization"    
I18n::Backend::KeyValue.send(:include, I18n::Backend::Pluralization)
```

**Comment by radar** [comment]
Hi there @ryan2johnson9, do you have an app which would help me reproduce this issue? That would be a huge help in my investigation of this bug.

Thank!

**Comment by ryan2johnson9** [comment]
No I don't have an app.  What's the best way to do that? My guess is:

setup a new rails app
set the git repository to my account
set the Gemfile to use similar versions of I18n that I am having a problem with
reproduce via a console to check error is there
push to git repo and let yourself know
you pull and run app on your machine

is that about right?

**Comment by dmitry** [comment]
@ryan2johnson9 this will be enough.

**Comment by ryan2johnson9** [comment]
https://github.com/ryan2johnson9/i18bug

This app shows the issue - to replicate in rails console run:

`I18n.t(:'i18n.plural.rule', :locale => 'en', :resolve => false)`

see the i18n.rb initializer

also you may need to adjust the redi password in that file.. or remove it..

**Comment by radar** [comment]
Thanks for the repro app @ryan2johnson9!

With this code I'm getting:

```
irb(main):001:0> I18n.t(:'i18n.plural.rule', :locale => 'en', :resolve => false)
I18n::InvalidLocale: "en" is not a valid locale
```

Is there something more that I need to set up?

**Comment by ryan2johnson9** [comment]
I am surprised as I do not get that.

I get

    ryan@ryan:~/rails_projects/i18bug$ rails c
    Running via Spring preloader in process 29925
    Loading development environment (Rails 4.1.6)
    2.3.0 :001 > I18n.t(:'i18n.plural.rule', :locale => 'en', :resolve => false)
    => "translation missing: en.i18n.plural.rule" 

I wonder what you may need to set up. Sorry I do not know.

**Comment by ryan2johnson9** [comment]
I have solved my issue:

I had to add in an initializer, which I called i18n_pluralization.rb the following code:

    require "i18n/backend/pluralization"
    I18n::Backend::KeyValue.send(:include, I18n::Backend::Pluralization)

p.s. I have `gem 'rails-i18n'` in my Gemfile

It may be related to the fact that I am using a chaned backend that first attempts to use redis, then falls back to looking up the .yml files. Not sure
