### ISSUE TITLE
Help offer

### ISSUE THREAD

**Issue by Chipairon** [svenfuchs/i18n#341]
This project seems a bit abandoned at the moment. There are several pull requests unattended, the CI tests are failing and links to resources are broken.

Can I contribute in any way to move things forward?

**Comment by sandstrom** [comment]
friendly ping @svenfuchs

**Comment by tigrish** [comment]
Help would definitely be very much appreciated as life, kids etc.. is getting in the way of me making any kind of significant contribution for the moment.

Mr @svenfuchs is the only one able to add maintainers though...

**Comment by sandstrom** [comment]
friendly ping @svenfuchs

**Comment by radar** [comment]
Hey all,

I talked to @svenfuchs about helping out on i18n yesterday over Twitter. He's given me write access to the repo and I can manage the issues and PRs.

No word on yet if I get some gem write access too, but it's a start.

I'll be going through the issues and PRs whenever I get a spare moment, so please let me know if there's any issues you want special attention on by tagging me in them.

 Also, if you want to help with triaging the issues and PRs then that would be appreciated too. Just leave a comment on it and tag me, and I can take it from there.

Let's work together on maintaining this wonderful gem!

Thanks everyone! :heart:

**Comment by radar** [comment]
@Chipairon and @sandstrom,

I am disappointed that in the 12 days since I posted this, you have not provided any assistance with the maintenance of this project. 

I could really do with the assistance and it'd be great if you could find some time to help out.

Thanks!

**Comment by sandstrom** [comment]
@radar I don't have any write access, so there isn't that much opportunity for me to help.

**Comment by radar** [comment]
You can at least help by triaging issues by leaving comments on them. Let me deal with the things which require write access.
