### ISSUE TITLE
A translation file with a blank parent key may wipe out child keys

### ISSUE THREAD

**Issue by dnl** [svenfuchs/i18n#342]
if i have two `.yml` like

``` yml
en:
  parent: 
     child: 'Child'
```

and 

``` yml
en:
  parent:
```

Then the `I18n.t('parent.child')` might not exist, because `I18n.t('parent')` is interpreted as an empty string in the second .yml file.

I think the deep merge done when importing the yml files should take into account blank keys possibly being `{}` and possibly being `''`, because yml is ambiguous

**Comment by simoniong** [comment]
ya, I hit the same issue, and debug for couple hours, finally figure out it is a empty parent key override everything!

**Comment by radar** [comment]
Hey @dnl,

I think that checking for a blank value or `{}` would mean that the process of merging these keys would be more than simply a `merge` (or `_deep_merge`, as it seems) call and therefore this library would take a performance hit for loading translations. 

For this reason I am hesitant to add a fix for this to i18n. If someone else comes across this issue, this GH issue can act as a sign post for what could possibly be going wrong.

Alternatively, if you can come up with a PR which does not adversely affect the performance of this gem, that would be most welcome.

Thanks!

**Comment by dnl** [comment]
Fair enough, it doesn't seem like a straightforward edge case to solve
