### ISSUE TITLE
Documentation needed

### ISSUE THREAD

**Issue by ghostsquad** [svenfuchs/i18n#356]
As someone new to this gem, the README doesn't provide enough information for getting started, and I didn't see any `examples` that I could look at.

**Comment by radar** [comment]
http://guides.rubyonrails.org/i18n.html should be plenty to get you started.

**Comment by dmitry** [comment]
@radar would be great to see this link in the README, so anyone else not familiar with i18n can easily check rails i18n guide.

**Comment by radar** [comment]
Done in 5cd5c9f. Thanks @ghostsquad and @dmitry.
