### ISSUE TITLE
Determine the beginning of the week day using locale

### ISSUE THREAD

**Issue by markedmondson** [svenfuchs/i18n#364]
[Date.beginning_of_week](http://apidock.com/rails/Date/beginning_of_week/class) assumes Monday as the beginning day of the week matching ISO-8601. [MomentJS](https://momentjs.com/docs/#/get-set/weekday/) use the locale to determine the day of the week into a more expected behaviour.

I quickly knocked together a gem to mimic this behaviour and was wondering if it's something you'd worth entertaining including in here?

https://github.com/markedmondson/i18n-beginning_of_week

Opinions welcome!

**Comment by radar** [comment]
I think it's OK having this as a separate gem for the meantime. Thanks for letting us know about it! :heart:
