### ISSUE TITLE
Translation using sub-tags and fallbacks broken since 0.8.1

### ISSUE THREAD

**Issue by daniel-rikowski** [svenfuchs/i18n#366]
## What I tried to do

I tried to translate a string with interpolated parameters where both the original string and a parameter are translated using sub-tag fallbacks.

This sounds contrived, but it can happen quite naturally in Rails applications, where I18n calls are hidden behind the Rails API. (For example when using `model_name`, `human_attribute_name`...)

Consider this:

```erb
<h1><%= t(:welcome, user: @customer) %></h1>
```
```ruby
class Customer
  def to_s
    I18n.t(:customer) # Normally this would be 'model_name.human`
  end
end
```
```ruby
I18n.locale = 'de-DE'        # not 'de'!
```
```yaml
de:       # not 'de-DE'!
  welcome: "Willkommen, %{user}!"
  customer: Kunde
```

## What I expected to happen

I'd expect 
```ruby
I18n.t(:welcome, user: @customer)
```

to return

> Willkommen, Kunde!

## What actually happened

Instead it returns

> Willkommen, translation missing: de-DE.customer

## Versions of i18n, rails, and anything else you think is neccessary

This happens with version 0.8.1. The previous versions work as expected.

I believe this is caused by https://github.com/svenfuchs/i18n/commit/c913b0a74325e8d2e426b82b4393655ff6670eb6

Note that  `Customer#to_s` is called from inside the original `translate` callstack.

Before https://github.com/svenfuchs/i18n/commit/c913b0a74325e8d2e426b82b4393655ff6670eb6 the "fallback lock" was stored in the `options` hash. That was bad style, but it had the benefit that the flag was local and visible to the current execution stack only. Now the `@fallback_locked` variable leaks across different calls of `translate`.

If reverting to using `options` is out of the question, I believe an additional parameter will be necessary...

----

I created a runnable application: https://gist.github.com/daniel-rikowski/0dc50fe88b6d6f2309eaf33af16a6d92 (You need to save both files in the same directory)

**Comment by chadrschroeder** [comment]
This will be fixed by https://github.com/svenfuchs/i18n/pull/374.

**Comment by radar** [comment]
Closing this as #374 has now been merged. There will be a release done sometime in the next 24 hours which will include this change. Thank you @chadrschroeder + @daniel-rikowski :)
