### ISSUE TITLE
Better error message when `I18n::TranslationMissingData` is rescued.

### ISSUE THREAD

**Issue by tgxworld** [svenfuchs/i18n#375]
## What I tried to do

```yaml
en:
  some_key: 'My name is %{name}'
```

```ruby
I18n.t('some_key', wrong_key: 'testing')
=>  "translation missing: en.some_key"
```

## What I expected to happen

```ruby
I18n.t('some_key', wrong_key: 'testing')
=>  "translation data missing: en.some_key"
```

## Versions of i18n, rails, and anything else you think is neccessary

I would like to propose a change for the default string that is returned when a `I18n::MissingTranslationData` is raised. 

```ruby
pry(main)> I18n.t('some_key', wrong_key: 'testing')
=> "translation missing: en.some_key"
pry(main)> I18n.t('some_ke', wrong_key: 'testing')
=> "translation missing: en.some_ke"
```

My confusion comes from the fact that `translation missing` can refer to a case where the key has not been defined as well as the case where the key has been defined but the variables are incorrect. I feel that returning `translation data missing: en.some_key` would be a much more accurate error message.

Thank you for your time! :heart:

**Comment by radar** [comment]
I believe https://github.com/svenfuchs/i18n/pull/371 might fix this issue? Could you please confirm for me @tgxworld?

**Comment by tgxworld** [comment]
@radar Thanks :) The new translation looks alittle odd to me though..

`super "translation data #{entry.inspect} can not be used with :count => #{count}. key '#{key}' is missing."`

It seems like it always assume that there will be a count key?

**Comment by ragesoss** [comment]
The new error message from #371 is only for pluralization, where there will always be a count. (The 'count' part if it was already part of the message; the key part at the end is what got added.)

This is a separate issue.

**Comment by ragesoss** [comment]
I can't replicate this. Here's what I get, which I think is sensible behavior:

```
pry(main)> I18n.t('some_key', wrong_key: 'testing')
=> I18n::MissingInterpolationArgument: missing interpolation argument :correct_key in "%{correct_key} message"
pry(main)> I18n.t('some_ke', wrong_key: 'testing')
=> "translation missing: en.some_ke"
```

**Comment by ragesoss** [comment]
@tgxworld It looks like maybe somewhere in your environment, `missing_interpolation_argument_handler` has been set differently from the default, so that it is handling the interpolation error the same way as a missing key error.

The gem lets you define an arbitrary handler for that error via `config.missing_interpolation_argument_handler=`, but by default, if I'm understanding it correctly, it should do something like what I posted above: raising an error.

**Comment by tgxworld** [comment]
@ragesoss Thanks for clarifying :+1: It does look like we have 

`I18n.config.missing_interpolation_argument_handler = proc { throw(:exception) }` by default. I'll investigate and fix it on our end.
