### ISSUE TITLE
A false default is inconsistent

### ISSUE THREAD

**Issue by jcoyne** [svenfuchs/i18n#379]
## What I tried to do
Passing a default with a single element array containing `false` seems to not give any default behavior.  This is inconsistent with a default of `false`(no wrapping array) or an array of strings.
I believe this is a regression in 0.8.3.

```ruby
I18n.translate('foo', default: [false])
=> "translation missing: en.foo"
I18n.translate('foo', default: false)
 => false
I18n.translate('foo', default: ['duh'])
"duh"
```

This is a problem for me because when I use the rails' `TranslationHelper#t` method, it wraps the default in an array automatically.

## What I expected to happen

```ruby
I18n.translate('foo', default: [false])
=> false
```

## What actually happened

```ruby
I18n.translate('foo', default: [false])
=> "translation missing: en.foo"
```

## Versions of i18n, rails, and anything else you think is neccessary

version 0.8.6 has this problem. I believe this behavior was changed in 0.8.3

----

Bonus points for providing an application or a small code example which reproduces the issue.

Thanks! :heart:

**Comment by radar** [comment]
Hi @jcoyne, thanks for getting in touch.

I am unable to reproduce this issue within a new Rails app. I am using i18n 0.8.6 and Rails 5.1.2.

I've created a new view and I've put this content in it:

```
<%= t(:foo, default: false) %>
<%= t(:foo, default: [false]) %>
```

Both return "false" for me. I do not see this "translation missing" error as you've shown.

Could you please provide me with an application which reproduces this issue?

Thanks!

**Comment by radar** [comment]
@jcoyne Please provide steps to reproduce this, otherwise I will be marking this issue as stale and closing it.

**Comment by jdelStrother** [comment]
I see this in a fresh Rails 5.1.4 install, with i18n 0.9.1

[rails51.zip](https://github.com/svenfuchs/i18n/files/1538906/rails51.zip)

For me, `t("foos", default: false)` returns `'<span class="translation_missing" title="translation missing: en.false">False</span>'`.

However, `I18n.t("foos", default: false)` returns `false`, suggesting the problem is with Rails when combined with i18n >= 0.8.3.   If I lower the i18n gem version to 0.8.1, both `t()` and `I18n.t()` return `false`.

**Comment by radar** [comment]
Thank you for filing this issue. I do not have any available time atm to investigate it. If you're _not_ seeing this bug with Rails but you are seeing this bug with Rails then I would consider that a Rails bug. You should file an issue on their repo also, and link this issue to it.

**Comment by rafaelfranca** [comment]
I tried with only i18n and I could reproduce this issue:

```
>> require 'i18n'
=> true
>> I18n::VERSION
=> "0.9.1"
>> I18n.config.enforce_available_locales = false
=> false
>> I18n.t("foo", default: [false])
=> "translation missing: en.foo"
>> I18n.t("foo", default: false)
=> false
```

I also tested with 0.8.1 and this behavior is the same:

```
>> gem 'i18n', '0.8.1'
=> true
>> require 'i18n'
=> true
>> I18n::VERSION
=> "0.8.1"
>> I18n.config.enforce_available_locales = false
=> false
>> I18n.t("foo", default: [false])
=> "translation missing: en.foo"
>> I18n.t("foo", default: false)
=> false
>> exit
```
