### ISSUE TITLE
Crashes when available_locales is [nil]

### ISSUE THREAD

**Issue by mkllnk** [svenfuchs/i18n#380]
## What I tried to do

Set `available_locales` from environment variable which was empty.

## What I expected to happen

It sees `available_locales` as uninitialised and ignores it. Or, if a value is necessary, it uses the chosen or default locale here.

## What actually happened

Initialising the application crashes:

```
.../gems/i18n-0.6.11/lib/i18n/config.rb:54:in `block in available_locales=': undefined method `to_sym' for nil:NilClass (NoMethodError)
	from .../gems/i18n-0.6.11/lib/i18n/config.rb:54:in `map'
	from .../gems/i18n-0.6.11/lib/i18n/config.rb:54:in `available_locales='
	from .../gems/i18n-0.6.11/lib/i18n.rb:35:in `available_locales='
```

## Versions of i18n, rails, and anything else you think is necessary

- ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]
- rails (3.2.21)
- i18n (0.6.11) and
- i18n (0.8.6) tested

**Comment by mkllnk** [comment]
Sure, here is an example repo: https://github.com/mkllnk/crash-i18n

I admit that it's a usage error to set `available_locales` to `[nil]`, but a more graceful error message or filtering out invalid values would be nice.

**Comment by radar** [comment]
Thank you very much :) I have just pushed https://github.com/svenfuchs/i18n/tree/patch-380. Could you please try this branch and let me know if the issue is fixed? If it is fixed, then I will merge this into master and do a new 0.8.x release. Thanks!

**Comment by mkllnk** [comment]
Now it crashes earlier at `config.i18n.default_locale = ENV["LOCALE"]`. But the error message is more useful. Seems like there has been another patch approaching a similar problem.

Instead of crashing, I would give a warning and then ignore the `nil` value. But I don't know what other people expect.

```
bundle exec rails console
.../gems/2.1.0/bundler/gems/i18n-b8817ee13386/lib/i18n.rb:284:in `enforce_available_locales!': nil is not a valid locale (I18n::InvalidLocale)
	from ...gems/2.1.0/bundler/gems/i18n-b8817ee13386/lib/i18n/config.rb:34:in `default_locale='
	from .../gems/2.1.0/bundler/gems/i18n-b8817ee13386/lib/i18n.rb:35:in `default_locale='
...
```

**Comment by radar** [comment]
I think crashing here is the most intuitive thing to do. It is clear from this error message that `default_locale=` is being passed nil.
