### ISSUE TITLE
Unintentional behaviour exhibited by the gettext helpers

### ISSUE THREAD

**Issue by lawrencepit** [svenfuchs/i18n#39]
Calling _("date") does not return the string "date". It returns the hash with date formats (from rails en.yml file). I think that's unintentional and unwanted behaviour of the gettext helpers.

Note that I don't use the GetText backend. Had I used it, then calling _("date") would result correctly in the string "date", but then I18n.t(:date) would also return "date" instead of the hash with date formats.

Given an AR backend, you get:

```
_("foo")            # SELECT * FROM translations WHERE key = 'foo' OR key LIKE 'foo.%'
I18n.t(:foo)        # SELECT * FROM translations WHERE key = 'foo' OR key LIKE 'foo.%'
```

I would expect something like:

```
_("foo")            # SELECT * FROM translations WHERE key = 'foo'
_("foo|bar")        # SELECT * FROM translations WHERE key = 'foo.bar'
```

Unfortunately that still doesn't solve the issue.

Anyone has a suggestion how to solve this?

**Comment by mmmries** [comment]
I just ran into this same issue. I have an ActiveRecord model that has a "name" field. This field is set by the user, so it was really surprising to me when i called:
```ruby
I18n.translate(category.name) # => {:formats=>{:default=>"%Y-%m-%d", :short=>"%b %d", :long=>"%B %d, %Y"}, :day_names=>["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"], :abbr_day_names=>["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"], :month_names=>[nil, "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"], :abbr_month_names=>[nil, "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"], :order=>["year", "month", "day"]}
```

this is the same thing as calling <code>::I18n.translate("date")</code>

One way to resolve this is to use a scope with my call to translate: <code>::I18n.translate("date", :scope => "categories")</code>

But it would be really nice if I could just have the guarantee that calls to ::I18n.translate would always return a string

**Comment by radar** [comment]
@mmmries I think in your case, you shouldn't have used the top-level namespace for your categories. Your solution of scoping them under `categories` was a wise choice.

@lawrencepit It's been a while, but is there a chance that you can provide me with a repro of this issue you're seeing?

**Comment by sandstrom** [comment]
Since this is such an old issue, I'd suggest closing this issue. We can reopen if it resurfaces.
