### ISSUE TITLE
ActiveSupport::JSON is super slow

### ISSUE THREAD

**Issue by stereobooster** [svenfuchs/i18n#397]
`ActiveSupport::JSON` is known to be super slow https://github.com/stereobooster/ruby-json-benchmark

What we can do is replace it with multi_json or add optional dependency for `oj` which has compatible mode with rails and fallback to `ActiveSupport::JSON` if `oj` not available.

Thanks! :heart:

**Comment by radar** [comment]
Patches welcome

**Comment by stevebissett** [comment]
This is no longer an issue because #398 is merged. Can we close it?

**Comment by radar** [comment]
Done!
