### ISSUE TITLE
I18n from .js.erb not updating values

### ISSUE THREAD

**Issue by siddushar** [svenfuchs/i18n#426]
I am using i18n for multi-language translation. everything is works well expect one scenario. i have one pop-up button on of my screen. The button label has to change according to language selected. the label will shows previously selected language not currently selected one.

The button will to ajax operation. one operation is completed button label only changed to previously selected language and rest app shows currently selected language.

in ruby console it puts correct but in JavaScript console it prints previously selected language
Ajax call as follows

// .js.erb code
var success = function() {
        console.log('<%= I18n.t('dashboard.update_button_caption') %>');
        console.log('<%= I18n.locale %>');
    }
    $.get("dashboard/ajax_update_user_data", queryString, success())

console.log in success call back always gives wrong locale when compared to controller action locale

can any one give solution to this.

Thanks!

**Comment by radar** [comment]
In production, assets are compiled ONCE. They do not update based on server side variables. You will need to come up with another way of solving this. Perhaps by getting the page to set a JS variable when it loads instead.
