### ISSUE TITLE
I18n::Backend::Chain and  initialized? init_translations methods

### ISSUE THREAD

**Issue by oniram88** [svenfuchs/i18n#432]
## What I tried to do

I want to check if the backends are already initialized and if not initialize it with 
I18n.backend.initialized?

## What I expected to happen

All chained backends will be initialized

## What actually happened

undefined method `initialized?' for #<I18n::Backend::Chain....

## Versions of i18n, rails, and anything else you think is neccessary

```
    i18n (0.8.6)
    rails (5.1.6)
```

------ 

Should the Chain class to be a "proxy" to al chained backends?

## Possible solutions:

```
 def initialized?
      backends.any? do |backend|
        !backend.initialized?
      end
    end

    def init_translations
      backends.each do |backend|
        backend.init_translations
      end
    end
```

**Comment by radar** [comment]
Could you please try this with a more modern i18n version?

**Comment by radar** [comment]
I am unable to reproduce this issue myself. Please provide some code that clearly replicates this issue, and ensure that it's still happening on a modern version of i18n.
