### ISSUE TITLE
I18n.translate does bad exception handling on arrays

### ISSUE THREAD

**Issue by strfry** [svenfuchs/i18n#435]
I found this consistency problem while debugging some i18n-related errors.

## What I tried to do

I18n.translate allows to process an array of translation keys at once, returning an array:

`result = I18n.t([:valid_string, :string_without translation])`

## What I expected to happen

MissingTranslation errors should lead to individual missing error strings:

`result == ["Valid Localized String", "translation missing: en-US.string_without_translation"]`

## What actually happened

Instead, control flow in I18n.translate is such, that in case of an error it forgets about the Array and returns a plain error message.

`result == "translation missing: en-US.string_without_translation"
`
## Versions of i18n, rails, and anything else you think is neccessary

I discovered this in i18n 0.7 (Rails 4 App), but it seems unchanged in current git master.

**Comment by strfry** [comment]
I tested with current master from this git, same problem.

**Comment by radar** [comment]
Consider mapping through the keys to get the expected result:

```ruby
[:test, :test2].map { |k| I18n.t(k) }
```
