### ISSUE TITLE
Add documentation about how to use this gem independently from rails

### ISSUE THREAD

**Issue by ohcibi** [svenfuchs/i18n#437]
This repositorys readme states that this gem can be used without rails. However there is no guide on how to do that. The rails guide isn't specifically useful as it implies all sorts of rails configuration magic which obviously is not available if this gem is used outside a rails project. My background is that I want to use this library to localize dates which shouldn't be that hard. 

1. Do I have to install `rails-i18n` (although the project "can be used without rails") to get local date names? I tried to install it but when trying to set `de` as language I still get the error that that language is not available. If there is *any* generic gem that carries translations ready to be used with this gem, please tell me. Google will only give me tutorials for rails
2. Please add a simple documentation about how to use this gem without rails. As mentioned its hard to impossible to google for documentation about such gems that is not about rails. Its a general problem which is common amongst all gems used inside rails, so sorry that I picked this one this create this issue.

**Comment by radar** [comment]
Thank you for your issue.

README now includes information about how to use this project without Rails. 

If you want to use the local date names, simply copy the `yml` files from the `rails-i18n` project into yours.
