### ISSUE TITLE
Regression(?) in v1.3.0, when used with `rails-i18n`

### ISSUE THREAD

**Issue by tom-lord** [svenfuchs/i18n#449]
## What I tried to do

"Composite" translations, where a hash is defined within the translation itself, have changed behaviour in `v1.2.0` and `v1.3.0`, *when this gem is used in a Rails application*.

## What I expected to happen/actually happened/versions

Here is a repo I have created demonstrating the behavioural changes:

https://github.com/tom-lord/i18n_regression

In particular, note that we have now *stringified* they keys of nested hashes (the last line says `"hello"`, not `:hello`).

Is the new behaviour desired? Maybe.

**Unlike before**, `v1.3.0` of this library's behaves the same way *with and without Rails*.

However, it's an undocumented change, which caught me off-guard. If this behaviour is expected, can we please add a regression test and ideally documentation?

**Comment by tom-lord** [comment]
Relates to:
https://github.com/svenfuchs/i18n/pull/422
https://github.com/svenfuchs/i18n/issues/443
https://github.com/svenfuchs/i18n/pull/444
https://github.com/svenfuchs/i18n/pull/445

**Comment by radar** [comment]
Thank you for reporting this. My understanding of the code in `core_ext/hash` means that this `hello` key _should_ be symbolised as well, due to the nature of `deep_symbolize_keys`. If it is not, then I would consider that a bug. 

A patch with at least a regression test would be appreciated. Similarly to #447, I will not have time to investigate this deeply until after Jan 2.

**Comment by alaz** [comment]
The issue is likely related to https://github.com/jruby/jruby/issues/5054 or some other of many refinements-related issues https://github.com/jruby/jruby/issues/5153.

**Comment by PikachuEXE** [comment]
@tom-lord 
Please take a look at #450 for possible fix

**Comment by PikachuEXE** [comment]
reopened?

**Comment by radar** [comment]
> possible fix

Not 100% confirmed by @tom-lord

I’m just being cautious after the #444 debacle.

**Comment by tom-lord** [comment]
@PikachuEXE @radar Thanks for the quick response/feedback/fix.

I'm happy with #450 as a fix for the issue. I think the new behaviour is best, for the majority of users.

Focusing on the "composite keys" situation, to summarise what's changed now:

`v1.1.1`:

- With rails: Keys are **symbols**, unless integer/boolean.
- Without rails: Keys are **strings**, unless integer/boolean.

`v1.2.0`:

- With rails: Keys are **symbols**, (_always_).
- Without rails: Keys are **strings**, unless integer/boolean.

`v1.3.0`:

- With rails: Keys are **strings**, unless integer/boolean.
- Without rails: Keys are **strings**, unless integer/boolean.

`master`:

- With rails: Keys are **symbols**, unless integer/boolean.
- Without rails: Keys are **symbols**, unless integer/boolean.

---

Both `v1.3.0` and `master` seem _valid_ to me; but both are a change in behaviour. In my opinion, making keys consistently symbols (the current master version) is best.

**Comment by radar** [comment]
Thank you for your confirmation @tom-lord. I agree that symbolising everything would make the API at least consistent, and also agree that it's a breaking change; something that should go into a new major release -- which is a long way off at this point in time.
