### ISSUE TITLE
`it` gem is broken by i18n 1.3

### ISSUE THREAD

**Issue by ghiculescu** [svenfuchs/i18n#452]
## What I tried to do

I'm not sure if this is a bug in `i18n` or in [`it`](https://github.com/iGEL/it), so I've reported it to both: https://github.com/iGEL/it/issues/26

But basically, when you are using **fallbacks**, `It.it` is crashing when attempting to do any interpolation.

## What I expected to happen | What actually happened

See https://github.com/iGEL/it/issues/26, which has several test scripts as well as their output.

## Versions of i18n, rails, and anything else you think is necessary

- i18n 1.3
- it 1.0 (latest; is over 18 months old, I don't think this is the culprit)
- rails 5.1.61 (haven't tested on other rails versions, but again I'm fairly sure this is unrelated)

**Comment by ghiculescu** [comment]
https://github.com/svenfuchs/i18n/pull/454 fixes this, at least for my use case.

**Comment by radar** [comment]
The fix for this has been released in i18n 1.4.0
